export interface Dxc_Model_Rlpd_Complainant {

    allCaseTypeId: string;//allCaseTypeId, string, รหัสประเภทหน่วยงานที่ดำเนินการต่อ],
    caseChannel: string;//caseChannel, string, ช่องทางการรับเรื่อง],
    caseId: number;//caseId, number, รหัสคดี],
    caseName: string;//caseName, string, ชื่อเรื่อง],
    caseRunningId: string;//caseRunningId, string, ลำดับเลขที่ทะเบียน],
    caseTypeName: string;//caseTypeName, string, ประเภทหน่วยงานที่ดำเนินการต่อ],
    centerApproveRemark: string;//centerApproveRemark, string, หมายเหตุจากส่วนกลาง],
    centerApproveStatus: number;//centerApproveStatus, number, สถานะการ Approve จากส่วนกลาง],
    centerSendDate: string;//centerSendDate, string, วันที่ส่งเข้าส่วนกลาง],
    channelId: number;//channelId, number, รหัสช่องทางการรับเรื่อง],
    checkRemark: string;//checkRemark, string, checkRemark],
    checkStatus: number;//checkStatus, number, การให้คำปรึกษา//เจ้าหน้าที่ตรวจสอบ]],
    dataId: string;//dataId, string, รหัสข้อมูล],
    dataSubmitDate: string;//dataSubmitDate, string, วันที่นำเข้าข้อมูล],
    dateCreate: string;//dateCreate, string, วันที่สร้างข้อมูล],
    dateUpdate: string;//dateUpdate, string, วันที่แก้ไขข้อมูล],
    departmentAbbriviation: string;//departmentAbbriviation, string, ชื่อย่อหน่วยงาน //ศูนย์]เจ้าของเรื่อง],
    departmentId: number;//departmentId, number, หน่วยงานเจ้าของเรื่อง],
    departmentName: string;//departmentName, string, ชื่อหน่วยงาน //ศูนย์]เจ้าของเรื่อง],
    districtId: number;//districtId, number, รหัสอำเภอ],
    editStatus: number;//editStatus, number, ยืนการการแก้ไขข้อมูล เจ้าหน้าที่/ที่ปรึกษากฎหมาย],
    email: string;//email, string, อีเมล์],
    entryDate: string;//entryDate, string, วันที่รับเรื่อง],
    kpi1DateEnd: string;//kpi1DateEnd, string, เวลาเริ่มลงทะเบียนแล้วเสร็จ],
    kpi1DateStart: string;//kpi1DateStart, string, เวลาเริ่มลงทะเบียน],
    kpi2DateEnd: string;//kpi2DateEnd, string, เวลาที่ให้คำปรึกษาแล้วเสร็จ],
    kpi2DateStart: string;//kpi2DateStart, string, เวลาที่เข้ารับคำปรึกษา],
    kpiDay: number;//kpiDay, number, kpiDay],
    kpiStatus: number;//kpiStatus, number, kpiStatus],
    logCount: number;//logCount, number, ลำดับที่ของ Log],
    oldCaseId: number;//oldCaseId, number, รหัส CASE_ID ของระบบเก่า],
    parentCaseId: string;//parentCaseId, string, ทะเบียนที่ส่งมาดำเนินการต่อ],
    personAddressAmphur: string;//personAddressAmphur, string, อำเภอ],
    personAddressFullText: string;//personAddressFullText, string, ที่อยู่],
    personAddressPostalCode: string;//personAddressPostalCode, string, รหัสไปรษณีย์],
    personAddressProvince: string;//personAddressProvince, string, จังหวัด],
    personAddressProvinceCode: string;//personAddressProvinceCode, number, รหัสจังหวัด],
    personAddressTumbon: string;//personAddressTumbon, string, ตำบล],
    personAddressTumbonCode: string;//personAddressTumbonCode, string, รหัสตำบล],
    personAge: number;//personAge, number, อายุ],
    personBirthDate: string;//personBirthDate, string, วันเกิด],
    personEducationLevelText: string;//personEducationLevelText, string, ระดับการศึกษา],
    personGivenName: string;//personGivenName, string, ชื่อ],
    personNationalIdentificationId: string;//personNationalIdentificationId, string, เลขประจำตัวประชาชนผู้ร้อง],
    personNationalityText: string;//personNationalityText, string, สัญชาติ],
    personOccupationText: string;//personOccupationText, string, อาชีพ],
    personPrefixName: string;//personPrefixName, string, คำนำหน้า],
    personReligionText: string;//personReligionText, string, ศาสนา],
    personSex: string;//personSex, string, เพศ],
    personSurName: string;//personSurName, string, นามสกุล],
    regionId: number;//regionId, number, ภูมิภาคที่ลงทะเบียน],
    regionName: string;//regionName, string, ภูมิภาคที่ลงทะเบียน],
    registerAcceptDate: string;//registerAcceptDate, string, registerAcceptDate],
    registerAcceptStatus: number;//registerAcceptStatus, number, registerAcceptStatus],
    registerCodeString: string;//registerCodeString, string, ],
    requestBy: number;//requestBy, number, ประเภทของผู้ถูกละเมิด],
    requestByEtc: string;//requestByEtc, string, รายละเอียดผู้มีส่วนเกี่ยวข้อง],
    statusId: number;//statusId, number, statusId],
    telephoneNumber: string;//telephoneNumber, string, เบอร์โทรศัพท์],
    userCenterApprove: number;//userCenterApprove, number, รหัสเจ้าหน้าที่ตรวจสอบการให้คำปรึกษา],
    userId: number;//userId, number, รหัสเจ้าหน้าที่ ที่รับลงทะเบียน],
    userStatus: number;//userStatus, number, สถานะการอนุญาตให้ใช้งาน],
    year: number;//year, number, ปีขึ้นทะเบียน],

}