export interface Dxc_Model_Sso_EmployeeEmployment{

    id : number;//id, number, รหัสข้อมูล, {pk : true}],
    personActiveStatus : number;//personActiveStatus, number, รหัสสถานะลูกจ้าง],
    personActiveStatusDescription : string;//personActiveStatusDescription, string, สถานะลูกจ้าง],
    personEmployeeBirthDate : string;//personEmployeeBirthDate, datetime, วันเกิด],
    personEmployeeBirthDateString : string;//personEmployeeBirthDateString, string, วันเกิด],
    personExpirationDate : string;//personExpirationDate, datetime, วันที่หมดอายุ],
    personExpirationDateString : string;//personExpirationDateString, string, วันที่หมดอายุ],
    personFirstName : string;//personFirstName, string, ขื่อ],
    personLastName : string;//personLastName, string, นามสกุล],
    personIdDescription : string;//personIdDescription, string, personIdDescription],
    personSex : string;//personSex, string, รหัสเพศ],
    personSexDescription : string;//personSexDescription, string, เพศ],
    personIdType : string;//personIdType, string, personIdType],
    personSsoNumber : string;//personSsoNumber, string, เลขประจำตัวประชาชน],
    personTitleCode : string;//personTitleCode, string, รหัสคำนำหน้าชื่อ],
    personTitleCodeDescription : string;//personTitleCodeDescription, string, คำนำหน้าชื่อ],
    dataSubmitDate : string;//dataSubmitDate, datetime, วันที่ปรับปรุงขอมูล],
    details : string;//detail, , ประวัติ, ],  
    accBran : number;//accBran, number, รหัสสาขา],
    accNo : number;//accNo, number, รหัส],
    companyName : string;//companyName, string, ชื่อบัริษัท],
    empResignDate : string;//empResignDate, datetime, วันที่],
    empResignDateString : string;//empResignDateString, string, วันที่],
    employStatus : string;//employStatus, string, รหัสสถานะลูกจ้าง],
    employStatusDesc : string;//employStatusDesc, string, สถานะลูกจ้าง],
    expStartDate : string;//expStartDate, string, หมดอายุ],
    expStartDateString : string;//expStartDateString, string, หมดอายุ],
    
    }